### ISSUE TITLE
AllAccessDisabled: All access to this object has been disabled

### ISSUE THREAD

**Issue by MaximeHeckel** [jimmynicol/image-resizer#38]
I get this error from S3 I guess. Do you have any suggestion about how to solve this problem ?
I have all the rights to my bucket. Therefore I shouldn't have any issues regarding access.

I think that's why I get the following error : 

```
GET /test/cr9YpNAdG.jpeg 500 643.251 ms - -
[resizer] new stream created!
[resizer] not valid image format
```

**Comment by jimmynicol** [comment]
Hmm, that is odd. So that error message arises from attempting to resize a file that is not one of the accepted formats (`jpeg`,`jpg`,`png`,`gif`) but clearly that is not the issue.

There were some issues a while back with file paths not being correctly passed through when there were no modifications listed. Maybe try adding a modifier like: `/s200/test/cr9YpNAdG.jpeg` and see that helps.

You could also try the new `sharp` branch that I have been working on which has a number of improvements. It will land sometime this week as the next evolution of the repo.
